In [1]:
import pandas as pd

/Users/nobu/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [6]:
df = pd.read_csv('DS.tsv', sep='\t')
df.head()

,Python,日本語,日本語.1,日本語.2,日本語.3,日本語.4
0,import pandas as pd,pandasをpdとしてインポートする,pandasをpdとしてインポートする,pandasをpdと名前を付けてインポート,pandasをpdとしてインポート,pandasをインポートし以降pdとして扱う
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み込み、dfとする,./data/lunch_box.csv'をカンマ区切りで読み込んで、dfとする,./data/lunch_box.csv'をカンマ区切りで読み込んだものをdfに代入,./data/lunch_box.csv'をカンマ区切りで読み、df とする,./data/lunch_box.csvをカンマ区切りで読み込み、dfとして扱う
2,df.head(3),dfの上3行を表示する,dfの初めの3行を表示する,dfの先頭の3行を表示,dfの最初の3行を表示させる,dfの先頭3行を表示する
3,df.head(),dfの上5行を表示する,dfの初めの5行を表示する,dfの先頭の5行を表示,dfの最初の5行を表示させる,dfの先頭5行を表示する
4,df.tail(),dfの下5行を表示する,dfの最後の5行を表示する,dfの最後の5行を表示,dfの最後の5行を表示させる,dfの末尾5行を表示する

In [14]:
df0 = df[['Python', '日本語']]
df0.head()

,Python,日本語
0,import pandas as pd,pandasをpdとしてインポートする
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み込み、dfとする
2,df.head(3),dfの上3行を表示する
3,df.head(),dfの上5行を表示する
4,df.tail(),dfの下5行を表示する

In [23]:
df1 = df[['Python', '日本語.1']]
df1 = df1.rename(columns={'日本語.1': '日本語'})
df1.head()

,Python,日本語
0,import pandas as pd,pandasをpdとしてインポートする
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み込んで、dfとする
2,df.head(3),dfの初めの3行を表示する
3,df.head(),dfの初めの5行を表示する
4,df.tail(),dfの最後の5行を表示する

In [24]:
df2 = df[['Python', '日本語.2']]
df2 = df2.rename(columns={'日本語.2': '日本語'})
df2.head()

,Python,日本語
0,import pandas as pd,pandasをpdと名前を付けてインポート
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み込んだものをdfに代入
2,df.head(3),dfの先頭の3行を表示
3,df.head(),dfの先頭の5行を表示
4,df.tail(),dfの最後の5行を表示

In [25]:
df3 = df[['Python', '日本語.3']]
df3 = df3.rename(columns={'日本語.3': '日本語'})
df3.head()

,Python,日本語
0,import pandas as pd,pandasをpdとしてインポート
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み、df とする
2,df.head(3),dfの最初の3行を表示させる
3,df.head(),dfの最初の5行を表示させる
4,df.tail(),dfの最後の5行を表示させる

In [26]:
df4 = df[['Python', '日本語.4']]
df4 = df4.rename(columns={'日本語.4': '日本語'})
df4.head()

,Python,日本語
0,import pandas as pd,pandasをインポートし以降pdとして扱う
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csvをカンマ区切りで読み込み、dfとして扱う
2,df.head(3),dfの先頭3行を表示する
3,df.head(),dfの先頭5行を表示する
4,df.tail(),dfの末尾5行を表示する

In [29]:
df_new = pd.concat([df0, df1, df2, df3, df4])
df_new.dropna()

,Python,日本語
0,import pandas as pd,pandasをpdとしてインポートする
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み込み、dfとする
2,df.head(3),dfの上3行を表示する
3,df.head(),dfの上5行を表示する
4,df.tail(),dfの下5行を表示する
...,...,...
148,pca = PCA(n_components=2),NaN
149,pca.fit(X_std),NaN
150,pca.components_,NaN
151,pca.explained_variance_,NaN
152,pca.explained_variance_ratio_,NaN

In [30]:
df_new = df_new.dropna()
df_new = df_new.reset_index(drop=True)
df_new

,Python,日本語
0,import pandas as pd,pandasをpdとしてインポートする
1,"df = pd.read_csv('./data/lunch_box.csv', sep=',')",./data/lunch_box.csv'をカンマ区切りで読み込み、dfとする
2,df.head(3),dfの上3行を表示する
3,df.head(),dfの上5行を表示する
4,df.tail(),dfの下5行を表示する
...,...,...
270,df.tail(),dfの末尾5行を表示する
271,df.shape,dfの大きさを表示する
272,df.index,dfのindexを表示する
273,df.columns,dfのcolumnsを表示する
274,"df[['name', 'kcal']].head()",dfのnameとkcalを抽出し、先頭5行を表示する

In [31]:
df_new.to_csv('ds.tsv', index=False, sep='\t')